### ISSUE TITLE
Framework

### ISSUE THREAD

**Issue by pietgeursen** [root-systems/dogstack#7]

**Comment by ahdinosaur** [comment]
okay, i want to think about MVP:

# 0.1

bin:

- `dogstack lint`: https://github.com/enspiral-root-systems/dogstack/issues/42
- `dogstack test`: https://github.com/enspiral-root-systems/dogstack/issues/43
- `dogstack dev`: https://github.com/enspiral-root-systems/dogstack/issues/44

# 0.2

bin:

- `dogstack server`: https://github.com/enspiral-root-systems/dogstack/issues/41

api:

- `dogstack.Log()`
- `dogstack.Server({ log, service, plugins })`
- `dogstack.Service({ services, plugins })`
- `dogstack.Client({ plugins })`
- `dogstack.Browser({ store, routes, renderer })`
- `dogstack.Store({ reducer, middlewares, enhancers })`
- `dogstack.Renderer({ plugins, enhancers, setup })`

# 0.3

rather than use `dogstack[method]` functions as glue code, remove the glue code entirely and export the custom params necessary to glue everything together as you want, at respective files `server.js`, `service.js`, `client.js`, `browser.js`, `store.js`, `renderer.js`, etc.

# 0.4

somehow enable us to split authentication to a separate repo, which we include into the example app.

will require us to describe a "dogstack plugin" as a set of topic directories, where each topic directory has files at specific file paths that determine what the file is doing. these files are then automatically composed into the app.

**Comment by iainkirkpatrick** [comment]
questions questions questions:

`dogstack:dev`: would this be a wrapper around something like budo to start with? or are you imagining something quite different?

0.3: this is referring to your thoughts around files being named a certain way within a certain directory structure just glueing themselves together ala `next.js`?

**Comment by ahdinosaur** [comment]
@iainkirkpatrick `dogstack dev` is the same as `catstack dev`, namely it wraps `node-dev` so your _next command_ runs in auto-restart mode. so most commonly you'd do `dogstack dev server`. no reason to use `budo` anymore since i wrote [`uify-server`](https://github.com/ahdinosaur/uify-server)

**Comment by ahdinosaur** [comment]
@iainkirkpatrick re 0.3, yes. then 0.4 is this but also applied to "plugins" in separate directories.
